#!/usr/bin/env bash

# Email contents of phishing_data.json are inspired by https://abnormal.ai/blog/email-security-phishing-templates
# Email metadata including senders, receivers, etc. generated by AI

PHISH_FILE="phishing_data.json"
LENGTH=$(jq '.subjects | length' "$PHISH_FILE")

for ((i=0; i<LENGTH; i++)); do
    SUBJECT=$(jq -r ".subjects[$i]" "$PHISH_FILE")
    BODY=$(jq -r ".bodies[$i]" "$PHISH_FILE")
    SENDER=$(jq -r ".senders[$i]" "$PHISH_FILE")
    RECEIVER=$(jq -r ".receivers[$i]" "$PHISH_FILE")
    URL=$(jq -r ".urls[$i]" "$PHISH_FILE")
    DATE=$(date '+%Y-%m-%d')

    json=$(jq -n \
    --arg SUBJECT "$SUBJECT" \
    --arg BODY "$BODY" \
    --arg SENDER "$SENDER" \
    --arg RECEIVER "$RECEIVER" \
    --arg DATE "$DATE" \
    --arg URL "$URL" \
    '{subject: $SUBJECT, body: $BODY, sender: $SENDER, receiver: $RECEIVER, date: $DATE, urls: $URL}')

    RESPONSE=$(curl -s -X POST http://localhost:5000/predict -H "Content-Type: application/json" -d "$json")
    PREDICTION=$(echo "$RESPONSE" | jq -r '.prediction')
    PROBABILITY=$(echo "$RESPONSE" | jq -r '.probability')
    ERROR=$(echo "$RESPONSE" | jq -r '.error // empty')

    if [[ -n "$ERROR" ]]; then
        echo "Test #$((i+1)) FAILED: $ERROR"
    elif [[ -n "$PREDICTION" && -n "$PROBABILITY" ]]; then
        echo "Test #$((i+1)) PASSED: Prediction=$PREDICTION, Probability=$PROBABILITY"
    else
        echo "Test #$((i+1)) WARNING: Unexpected response: $RESPONSE"
    fi
done